## Travis configuration file for covmat

language: R

sudo: required

warnings_are_errors: false

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --as-cran"

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_github hadley/testthat
  - ./travis-tool.sh install_github jimhester/covr
  - ./travis-tool.sh install_github yihui/knitr
  - ./travis-tool.sh install_github arorar/FactorAnalytics

script: ./travis-tool.sh run_tests

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
  on_success: always
  on_failure: always