## Travis configuration file for covmat

language: r

sudo: required

warnings_are_errors: false

r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --as-cran"

r_github_packages:
  - hadley/devtools
  - hadley/testthat
  - jimhester/covr

install:
  - Rscript -e 'install.packages("factorAnalytics", repos="http://R-Forge.R-project.org")'
  - Rscript -e 'install.packages("devtools")'
after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
  on_success: always
  on_failure: always